server {
    listen 80;
    server_name localhost;

    # Racine du dossier contenant les fichiers
    root /usr/share/nginx/html;

    # 1. Redirection automatique de la racine (/) vers le français (/fr/)
    location = / {
        return 301 /fr/;
    }

    # 2. Configuration pour la version Française
    location /fr/ {
        # Important pour Angular : si le fichier n'existe pas, renvoyer l'index.html du dossier fr
        try_files $uri $uri/ /fr/index.html;
    }

    # 3. Configuration pour la version Anglaise
    location /en/ {
        try_files $uri $uri/ /en/index.html;
    }

    # Gestion des erreurs globales (optionnel)
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}